package main.resources.PPMA;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

/**
 * This test case is meant to Sign Up a new account
 */
public class TC13 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().window().maximize();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC13() {
    driver.get("http://localhost/ppma/");
    driver.findElement(By.cssSelector(".btn-default")).click();
    driver.findElement(By.id("user")).sendKeys("admin321");
    driver.findElement(By.id("pwd")).sendKeys("admin321");
    driver.findElement(By.id("pwd1")).sendKeys("admin321");
    driver.findElement(By.id("email")).sendKeys("321@163.com");
    driver.findElement(By.id("chk")).click();
    assertThat(driver.switchTo().alert().getText(), is("Successfully signup, now please sign in!"));
  }
}
