  package main.resources.PPMA;// Generated by Selenium IDE

  import org.junit.After;
  import org.junit.Before;
  import org.junit.Test;
  import org.openqa.selenium.By;
  import org.openqa.selenium.JavascriptExecutor;
  import org.openqa.selenium.WebDriver;
  import org.openqa.selenium.firefox.FirefoxDriver;

  import java.util.HashMap;
  import java.util.Map;

  /**
   * This test case is meant to Change Password in PPMA v9.08
   */
  public class TC7 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
      driver = new FirefoxDriver();
      driver.manage().window().maximize();
      js = (JavascriptExecutor) driver;
      vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
      driver.quit();
    }
    @Test
    public void tC7() throws InterruptedException {
      driver.get("http://localhost/Password-Manager-9.0/");
      driver.findElement(By.id("user")).clear();
      driver.findElement(By.id("user")).sendKeys("heli123");
      driver.findElement(By.id("pwd")).clear();
      driver.findElement(By.id("pwd")).sendKeys("heli123");
      driver.findElement(By.id("check")).click();
      Thread.sleep(1000);
      driver.findElement(By.linkText("Settings")).click();
      driver.findElement(By.linkText("Change Password")).click();
      driver.findElement(By.id("oldpassword")).sendKeys("heli123");
      driver.findElement(By.id("pwd")).sendKeys("heli123");
      driver.findElement(By.id("pwd1")).sendKeys("heli123");
      driver.findElement(By.id("changepw")).click();

    }
  }




