package main.resources.PHPSHE;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;


/**
 * This test case is meant to Collect Commodity
 */
public class TC3 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().window().maximize();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC3() throws InterruptedException {
    driver.get("http://localhost/phpshe-free_v1.5/");
    driver.findElement(By.linkText("登录")).click();
    driver.findElement(By.name("user_name")).clear();
    driver.findElement(By.name("user_name")).sendKeys("admin123");
    driver.findElement(By.name("user_pw")).clear();
    driver.findElement(By.name("user_pw")).sendKeys("admin123");
    driver.findElement(By.xpath("//input[@value='立即登录']")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//img[@title='HUAWEI Mate40']")).click();
    Thread.sleep(5000);
    driver.findElement(By.linkText("/html/body/div[7]/div[3]/table/tbody/tr[5]/td[2]/a[2]")).click();
    driver.findElement(By.linkText("[退出]")).click();
  }
}
