package main.resources.Claroline;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.support.ui.Select;

/**
 * This test case is meant to Create Course
 */
public class TC2 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().window().maximize();
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC2() throws InterruptedException {
    driver.get("http://localhost/claroline90/");
    driver.findElement(By.id("login")).clear();
    driver.findElement(By.id("login")).sendKeys("admin");
    driver.findElement(By.id("password")).clear();
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.name("submitAuth")).click();
    Thread.sleep(500);
    driver.findElement(By.linkText("Create a course site")).click();
    driver.findElement(By.id("course_title")).clear();
    driver.findElement(By.id("course_title")).sendKeys("Data Structure");
    driver.findElement(By.id("course_officialCode")).clear();
    driver.findElement(By.id("course_officialCode")).sendKeys("ROM2122");
    new Select(driver.findElement(By.id("course_category"))).selectByVisibleText("(SC) Sciences");
    driver.findElement(By.id("course_departmentName")).clear();
    driver.findElement(By.id("course_departmentName")).sendKeys("Software Department");
    driver.findElement(By.id("course_extLinkUrl")).clear();
    driver.findElement(By.id("course_extLinkUrl")).sendKeys("www.seu.edu.cn");
    driver.findElement(By.name("changeProperties")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}
